config/routes.rb
Statusboard::Application.routes.draw do
  post "services/flickr_user_photos", :via => :post 

  resources :boards do
    resources :widgets
  end

end

app/models/board.rb
class Board
  include Mongoid::Document
  field :title
  field :content

  embeds_many :widgets
end

app/models/widget.rb
class Widget
  include Mongoid::Document
  
  field :title, default: "No Title"
  field :location, type: Array, default: [0,0]
  field :params, type: Array, default: {}
  field :size, type: Array, default: [0,0]
  field :widgettype, default: "None"

  validates_presence_of :location, :size, :widgettype

  embedded_in :board, :inverse_of => :widgets

  attr_accessible :location, :size, :widgettype, :params, :title

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  # GET /boards
  # GET /boards.json
  def index
    @boards = Board.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @boards }
    end
  end

  # GET /boards/1
  # GET /boards/1.json
  def show
    @board = Board.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/new
  # GET /boards/new.json
  def new
    @board = Board.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @board }
    end
  end

  # GET /boards/1/edit
  def edit
    @board = Board.find(params[:id])
  end

  # POST /boards
  # POST /boards.json
  def create
    @board = Board.new(params[:board])

    respond_to do |format|
      if @board.save
        format.html { redirect_to @board, notice: 'Board was successfully created.' }
        format.json { render json: @board, status: :created, location: @board }
      else
        format.html { render action: "new" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /boards/1
  # PUT /boards/1.json
  def update
    @board = Board.find(params[:id])

    respond_to do |format|
      if @board.update_attributes(params[:board])
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boards/1
  # DELETE /boards/1.json
  def destroy
    @board = Board.find(params[:id])
    @board.destroy

    respond_to do |format|
      format.html { redirect_to boards_url }
      format.json { head :no_content }
    end
  end

  def widgets
    @board = Board.find(params[:id])
    render :json => "nothing"
  end
end

app/controllers/services_controller.rb
require 'flickraw'

FlickRaw.api_key="302a4a49d1f85726239821d77caa7f50"
FlickRaw.shared_secret="42087084f2b3168f"

class ServicesController < ApplicationController

  def flickr_user_photos

    # The params[:user_id] isn't working on the heroku

    if $temp
      p "using cache"
      photos = $temp
    else 

      # // params is adding quotes, so :user_id is "\"97358734@N03\""

      # sets = flickr.photosets.getList(:user_id => params[:user_id])
      sets = flickr.photosets.getList(:user_id => "97358734@N03")

      
      ids = []
      sets.each { |set| ids << set.id}
      
      photos = []

      ids.each do |id|
        ps_req = flickr.photosets.getPhotos(:photoset_id => id, :extras => 'url_m')
        photos.concat(ps_req.photo)
      end
      $temp = photos

    end

    render :json => photos.shuffle

  end
end

app/controllers/widgets_controller.rb
require 'json'
class WidgetsController < ApplicationController

  # GET /widgets
  # GET /widgets.json
  def index
    @board = Board.find(params[:board_id])
    @widgets = @board.widgets

    # @widgets = @widgets.to_json
    # p @widgets.first.delete(:_id)
    # @widgets.each{|widget| widget.store(:id, widget.delete(:_id))}



    render json: @widgets

    # respond_to do |format|
    #   format.html # index.html.erb
    #   format.json { render json: @widgets }
    # end
  end

  # GET /widgets/1
  # GET /widgets/1.json
  def show
    @widget = Board.find(params[:board_id]).widgets.where('_id' => Moped::BSON::ObjectId(params[:id])).first
    p @widget
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/new
  # GET /widgets/new.json
  def new
    @widget = Widget.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @widget }
    end
  end

  # GET /widgets/1/edit
  def edit
    @widget = Widget.find(params[:id])
  end

  # POST /widgets
  # POST /widgets.json
  def create
    @widget = Widget.new(params[:widget])

    respond_to do |format|
      if @widget.save
        format.html { redirect_to @widget, notice: 'Widget was successfully created.' }
        format.json { render json: @widget, status: :created, location: @widget }
      else
        format.html { render action: "new" }
        format.json { render json: @widget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /widgets/1
  # PUT /widgets/1.json
  def update
    @board = Board.find(params[:board_id])
    @widget = @board.widgets.where('_id' => Moped::BSON::ObjectId(params[:id])).first
    p @widget

    if params[:location] 
      @widget.location = params[:location]
    end
     
    if params[:size]
      @widget.size = params[:size]
    end

    if params[:params]
      @widget.params = params[:params]
    end

    if params[:title]
      @widget.title = params[:title]
    end
    
    if params[:"new-content"]
      p params["new-content"]
      @widget.params["content"] = params[:"new-content"]
      @widget.save

      render :json => params[:"new-content"]
      return
    end

    @widget.save

    p "in update"
    render :text => "updated"
    # respond_to do |format|
    #   if @widget.update_attributes(params[:widget])
    #     format.html { redirect_to @widget, notice: 'Widget was successfully updated.' }
    #     format.json { head :no_content }
    #   else
    #     format.html { render action: "edit" }
    #     format.json { render json: @widget.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  # DELETE /widgets/1
  # DELETE /widgets/1.json
  def destroy
    @widget = Widget.find(params[:id])
    @widget.destroy

    respond_to do |format|
      format.html { redirect_to widgets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/widgets_helper.rb
module WidgetsHelper
end

app/views/boards/_form.html.haml
= form_for(@board) do |f|
  - if @board.errors.any?
    #error_explanation
      %h2
        = pluralize(@board.errors.count, "error")
        prohibited this board from being saved:
      %ul
        - @board.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :title
    %br/
    = f.text_field :title
  .field
    = f.label :description
    %br/
    = f.text_area :description
  .actions
    = f.submit

app/views/boards/edit.html.haml
%h1 Editing board
= render 'form'
= link_to 'Show', @board
|
\#{link_to 'Back', boards_path}

app/views/boards/index.html.haml
%h1 Current Dashboards
%table
  %tr
    %th Name
    %th Description
    %th
    %th
    %th
  - @boards.each do |board|
    %tr
      %td= board.title
      %td= board.description

      %td= link_to 'Show', board
      %td= link_to 'Edit', edit_board_path(board)
      %td= link_to 'Destroy', board, method: :delete, data: { confirm: 'Are you sure?' }
%br/
= link_to 'New Board', new_board_path

app/views/boards/new.html.haml
%h1 New board
= render 'form'
= link_to 'Back', boards_path

app/views/boards/show.html.haml
#board-page

.gridster
  %ul

%p#notice= notice
%p
  %b Title:
  = @board.title
%p
  %b Description:
  = @board.description

- @board.widgets.each do |widget|
  = widget.attributes
  %br

#content
- 5.times do
  %br

= link_to 'Edit', edit_board_path(@board)
|
\#{link_to 'Back', boards_path}

#counter

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Statusboard
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    = yield

app/views/services/flickr.html.haml
%h1 Services#flickr
%p Find me in app/views/services/flickr.html.haml

app/views/widgets/_form.html.erb
<%= form_for(@widget) do |f| %>
  <% if @widget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@widget.errors.count, "error") %> prohibited this widget from being saved:</h2>

      <ul>
      <% @widget.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :params %><br />
    <%= f.text_field :params %>
  </div>
  <div class="field">
    <%= f.label :size %><br />
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :widgettype %><br />
    <%= f.text_field :widgettype %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/widgets/edit.html.erb
<h1>Editing widget</h1>

<%= render 'form' %>

<%= link_to 'Show', @widget %> |
<%= link_to 'Back', widgets_path %>

app/views/widgets/index.html.haml
%h1 Listing widgets
%table
  %tr
    %th Location
    %th Params
    %th Size
    %th Widgettype
    %th
    %th
    %th
  - @widgets.each do |widget|
    %tr
      %td= widget.location
      %td= widget.params
      %td= widget.size
      %td= widget.widgettype
      %td= link_to 'Show', widget
      %td= link_to 'Edit', edit_widget_path(widget)
      %td= link_to 'Destroy', widget, method: :delete, data: { confirm: 'Are you sure?' }
%br/
//= link_to 'New Widget', new_widget_path

app/views/widgets/new.html.erb
<h1>New widget</h1>

<%= render 'form' %>

<%= link_to 'Back', widgets_path %>

app/views/widgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Location:</b>
  <%= @widget.location %>
</p>

<p>
  <b>Params:</b>
  <%= @widget.params %>
</p>

<p>
  <b>Size:</b>
  <%= @widget.size %>
</p>

<p>
  <b>Widgettype:</b>
  <%= @widget.widgettype %>
</p>


<%= link_to 'Edit', edit_widget_path(@widget) %> |
<%= link_to 'Back', widgets_path %>